### ISSUE TITLE
openshift compatability

### ISSUE THREAD

**Issue by msillence** [curl/curl-container#10]
allow openshift to run entrypoint.sh https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html

specifically section "Support Arbitrary User IDs"

By default, OpenShift Container Platform runs containers using an arbitrarily assigned user ID. This provides additional security against processes escaping the container due to a container engine vulnerability and thereby achieving escalated permissions on the host node

I was going to propose adding the below to the docker file but it looks like your image is built in a different way?

RUN chmod a+rx /entrypoint.sh

**Comment by xquery** [comment]
yes, we use buildah ... FWIW most of the open issues are related to this area ... fix coming soon

**Comment by xquery** [comment]
could you please check with quay.io/curl/curl:8.1.2

**Comment by msillence** [comment]
Looks good, many thanks for the quick fix
