### ISSUE TITLE
Manifest missing mediaType

### ISSUE THREAD

**Issue by spurin** [curl/curl-container#12]
The manifest has no top level mediaType set and I believe that because of this, it doesn't render as expected in the Docker Hub web view. It should show the OS/Arch options.

The following is an example of ubuntu: https://explore.ggcr.dev/?image=ubuntu%3Alatest

VS the current curlimages/curl: https://explore.ggcr.dev/?image=curlimages/curl@sha256:9d679ae7718688259258a3ea3862963023f32eae630052fde63aae5e9919a90d&mt=application%2Fvnd.oci.image.index.v1%2Bjson&size=1043

Example in Docker Hub, note that OS/Arch is empty:

![image](https://github.com/curl/curl-container/assets/850464/171d111a-7e18-46a1-8c28-6d8f24904636)

Updating the buildah manifest push command with

--format v2s1
--format v2s2
--format oci

May possibly resolve this.

**Comment by spurin** [comment]
Referenced on Docker Hub - https://github.com/docker/hub-feedback/issues/2329

**Comment by xquery** [comment]
well --format oci does not work ... will try the others

**Comment by xquery** [comment]
checking https://explore.ggcr.dev/?image=curlimages%2Fcurl%3A8.1.2 ... seems to have correct media type

**Comment by spurin** [comment]
Thanks @xquery 

Looking good!

<img width="1252" alt="image" src="https://github.com/curl/curl-container/assets/850464/e8389c89-be90-4f78-b926-c204a17de06c">
