### ISSUE TITLE
version 8.1.2 breaks container image jobs under arm64 architecture

### ISSUE THREAD

**Issue by sveneisenmann** [curl/curl-container#3]
Hi,

the current 'latest' tag (version 8.1.2) breaks container image jobs under arm64 architecture.

We are using the image regularly in a gitlab ci/cd job and are receiving the following error message:

```
ERROR: Job failed (system failure): Error response from daemon: unable to find user curl_user: no matching entries in passwd file (exec.go:78:0s)
```

Please let me know, if I can support troubleshooting any further.

Best regards

**Comment by xquery** [comment]
thx for the report - are you able to manually test that env eg.

```
podman run -it docker.io/curlimages/curl:latest -V
```
should return something like
```
curl 8.1.2 (x86_64-pc-linux-musl) libcurl/8.1.2 OpenSSL/3.1.0 zlib/1.2.13 brotli/1.0.9 libidn2/2.3.4 libssh2/1.10.0 nghttp2/1.53.0
Release-Date: 2023-05-30
Protocols: dict file ftp ftps gopher gophers http https imap imaps mqtt pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: alt-svc AsynchDNS brotli HSTS HTTP2 HTTPS-proxy IDN IPv6 Largef
```

**Comment by xquery** [comment]
actually have reproduced locally

```
 podman run -it localhost/curl-linux-arm64:master -V
WARNING: image platform (linux/arm64/v8) does not match the expected platform (linux/amd64)
Error: unable to find user curl_user: no matching entries in passwd file
```

looks like somewhere the arch is assuming /v8 ... this is new behaviour

**Comment by spurin** [comment]
Just came by to report the same issue, I noticed it when referencing curlimages/curl:latest

```
% docker run -it curlimages/curl sh
docker: Error response from daemon: unable to find user curl_user: no matching entries in passwd file.
ERRO[0000] error waiting for container:
```

It threw me as I was seeing this reported by the kubelet -

```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  26s                default-scheduler  Successfully assigned default/curl to control-plane
  Normal   Pulled     25s                kubelet            Successfully pulled image "curlimages/curl:latest" in 809.51675ms (809.529667ms including waiting)
  Warning  Failed     25s                kubelet            Error: failed to create containerd container: mount callback failed on /var/lib/rancher/k3s/agent/containerd/tmpmounts/containerd-mount4116084050: no users found
```

Thanks by the way, love your efforts with curlimages/curl 👍

**Comment by EricChen1248** [comment]
Came to report same issue.

On a podman machine I get
```
ERROR: Job failed (system failure): unable to upgrade to tcp, received 409 (exec.go:71:0s)
```

On a docker machine I get the same curl_user error as [sveneisenmann](https://github.com/sveneisenmann)

Thanks for the work though, this container is great for running super lightweight ci/cd jobs for web testing.

**Comment by JRemitz** [comment]
Noticed [this line which seems unusual.](https://github.com/curl/curl-container/blame/63d895db5f76933ee7c0ec94cddd2d6abb40a1a7/create_base_image.sh#L92) Was this the output of something automated?

**Comment by xquery** [comment]
no that was an error but does not break anything - will be removing soon - thx for the quick 'eagle eyes'!

**Comment by xquery** [comment]
reproduces:

```
docker run -it --platform linux/amd64 curlimages/curl:8.1.2 -V
```

other arches are fine, ex:

```
docker run -it --platform linux/arm64 curlimages/curl:8.1.2 -V
```
still investigating ...

**Comment by spurin** [comment]
Hi @xquery,

Looking at this, using https://explore.ggcr.dev/?image=curlimages/curl (current toplevel [link](https://explore.ggcr.dev/?image=curlimages/curl@sha256:9d679ae7718688259258a3ea3862963023f32eae630052fde63aae5e9919a90d&mt=application%2Fvnd.oci.image.index.v1%2Bjson&size=1043))

We can see the hierarchy for each architecture -

AMD64: [Link](https://explore.ggcr.dev/?image=curlimages/curl@sha256:d50e9aca7725d72e48abdbbe09d022e63b26b8af7853c91d05bddabd569aa37f&mt=application%2Fvnd.oci.image.manifest.v1%2Bjson&size=660)
ARM64: [Link](https://explore.ggcr.dev/?image=curlimages/curl@sha256:e9873010d7b30eb89236956c335bd1911c4d04106a02bb058da77018b4e7c32c&mt=application%2Fvnd.oci.image.manifest.v1%2Bjson&size=656)

Breaking this down further, each platform specific consists of 3 layers.  It appears to be Alpine, Main App, then an Empty Layer (which can occur for the likes of environment variables or other container entities that dont write a layer).

AMD64: [Link](https://explore.ggcr.dev/?image=curlimages/curl@sha256:d50e9aca7725d72e48abdbbe09d022e63b26b8af7853c91d05bddabd569aa37f&mt=application%2Fvnd.oci.image.manifest.v1%2Bjson&size=660)
  - Alpine: [Link](https://explore.ggcr.dev/fs/curlimages/curl@sha256:8a49fdb3b6a5ff2bd8ec6a86c05b2922a0f7454579ecc07637e94dfd1d0639b6/?mt=application%2Fvnd.oci.image.layer.v1.tar%2Bgzip&size=3397490)
  - Main App (curl): [Link](https://explore.ggcr.dev/fs/curlimages/curl@sha256:d262d6ffbee7e9ff7dd4690e691f8c7b3c1931fa1007c0c1a4997e9b39a7ada1/?mt=application%2Fvnd.oci.image.layer.v1.tar%2Bgzip&size=4652060)
  - Empty Layer: [Link](https://explore.ggcr.dev/fs/curlimages/curl@sha256:4ca545ee6d5db5c1170386eeb39b2ffe3bd46e5d4a73a9acbebc805f19607eb3/?mt=application%2Fvnd.oci.image.layer.v1.tar%2Bgzip&size=42)
  
ARM64: [Link](https://explore.ggcr.dev/?image=curlimages/curl@sha256:e9873010d7b30eb89236956c335bd1911c4d04106a02bb058da77018b4e7c32c&mt=application%2Fvnd.oci.image.manifest.v1%2Bjson&size=656)
  - Alpine: [Link](https://explore.ggcr.dev/fs/curlimages/curl@sha256:08409d4172603f40b56eb6b76240a1e6bd78baa0e96590dc7ff76c5f1a093af2/?mt=application%2Fvnd.oci.image.layer.v1.tar%2Bgzip&size=3342848)
  - Main App (curl): [Link](https://explore.ggcr.dev/fs/curlimages/curl@sha256:4199f3fe0a8a31e26f2ba66984e97a9d39daf0848c42f23de2ddc910926ec9af/?mt=application%2Fvnd.oci.image.layer.v1.tar%2Bgzip&size=417)
  - Empty Layer: [Link](https://explore.ggcr.dev/fs/curlimages/curl@sha256:4ca545ee6d5db5c1170386eeb39b2ffe3bd46e5d4a73a9acbebc805f19607eb3/?mt=application%2Fvnd.oci.image.layer.v1.tar%2Bgzip&size=42)
  
Clicking the link and comparing the files in the 'Main App (curl)' layer between AMD64 and ARM64, suggests that the build process may have failed for this layer.  For convenience, screenshot comparison -

AMD64 -

<img width="890" alt="image" src="https://github.com/curl/curl-container/assets/850464/64149f22-732c-4bae-a5c8-a2c5943e2cef">

ARM64 -

<img width="901" alt="image" src="https://github.com/curl/curl-container/assets/850464/6dc80a6e-9c24-47c6-830d-1f97832adfb3">

Hopefully this helps with the troubleshooting.

**Comment by xquery** [comment]
image error is just side effect of attempting to remove manifest (which does not exist)  ... thx for the debug info ... once I have a few free cycles will investigate more deeply

**Comment by davesmith00sky** [comment]
Just dropped by to report the same issue, thanks for investigating. 👍 

```
➜  ~ docker run --rm curlimages/curl:8.1.2 --version
docker: Error response from daemon: unable to find user curl_user: no matching entries in passwd file.
```

**Comment by xquery** [comment]
in the short term (a few days at most I hope) have removed support for arm64 ... this is a deeper issue related to buildah (side effect of new container build systm)... once that is addressed arm64 support will come back.

**Comment by Jordan9500** [comment]
Hi, I am getting the same issue posted here but for `s390x`
```
docker run -it --platform linux/s390x curlimages/curl:8.1.2 -V
.......
docker: Error response from daemon: unable to find user curl_user: no matching entries in passwd file.
```

And get a mount faillure similar to: https://github.com/curl/curl-container/issues/3#issuecomment-1579321882 for kubelet (Which also threw me off):
```
Events:
  Type     Reason     Age               From               Message
  ----     ------     ----              ----               -------
  Normal   Scheduled  22s               default-scheduler  Successfully assigned kube-system/ext-res-updater-xsvrc to node
  Normal   Pulled     21s               kubelet            Successfully pulled image "curlimages/curl" in 298.088945ms (298.103129ms including waiting)
  Warning  Failed     21s               kubelet            Error: failed to create containerd container: mount callback failed on /var/lib/containerd/tmpmounts/containerd-mount989058884: no users found
```
The workaround mentioned for using the prior tags (`8.1.1`) works. 

Please let me know if this needs a different issue. With this issue focusing on the arm64 architecture.

Many Thanks!

**Comment by xquery** [comment]
just to let everyone know - a few free cycles have appeared ... raising PR shortly

**Comment by xquery** [comment]
looks like that PR works ... the issue was using buildah in a container modulo qemu ... though the delay was me getting confused by a completely different qemu problem in my local dev env (and me thinking that was the issue in CI) ... release will happen in next 24 hrs (if not sooner).

**Comment by xquery** [comment]
all pls test out latest release

**Comment by xquery** [comment]
everyone please test with latest releases (from quay/curl/curl:8.1.2 or docker.io/curlimages/curl:8.1.2)

apologies for the churn - migrating to a new build system came with some risks of disruption - hoping we are now past it.
