### ISSUE TITLE
CApath is not set anymore in 8.11.1

### ISSUE THREAD

**Issue by ypsah** [curl/curl-container#72]
Until version `8.11.1`, `curl` was compiled with `ca-path` set to `/etc/ssl/certs`: https://github.com/curl/curl-container/actions/runs/11700739500/job/32585349804#step:8:4844, but it isn't the case with `8.11.1`: https://github.com/curl/curl-container/actions/runs/12272458759/job/34241246041#step:8:4848.

**Comment by ypsah** [comment]
The relevant piece of code in `curl` seems to be: https://github.com/curl/curl/blob/6eb86e428d96288c57661f85a798fa8fbc6bd95e/acinclude.m4#L1186. It does not appear to have changed.

I do not get how the following check passed for `8.11.0`:
```m4
ls "$a"/[[0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f][0-9a-f]].0
```

**Comment by ypsah** [comment]
Ah, I think I found it: https://gitlab.alpinelinux.org/alpine/aports/-/commit/8be9a640624fc5e8d106cb72944ec5b986a503d5

This change in `alpine` made `curl` depend only on `ca-certificates-bundle` and not `ca-certificates`.

`ca-certificates-bundle` only ships a minimal set of certificates:
```console
$ apk info -L ca-certificates-bundle
ca-certificates-bundle-20240705-r0 contains:
etc/ssl/cert.pem
etc/ssl/certs/ca-certificates.crt
etc/ssl1.1/cert.pem
etc/ssl1.1/certs
```

While `ca-certificates` ships many more files, including some that match the `/etc/ssl/certs/[0-9a-f]{8}.0` regexp.

**Comment by ypsah** [comment]
Should `ca-certificates` be added as an explicit build dependencies?

Or maybe the check in `curl` should be reworked to also match a single `ca-certificates.crt`? Maybe even any file? I could not find a reasoning in the git history for why the check was written this way in the first place: https://github.com/curl/curl/commit/86cbb23282bee426439fc969d09a462acac0abe9.

**Comment by jay** [comment]
It looks as though alpine switched curl to use a single certificate bundle rather than a directory full of certificates (ie capath). The latter definitely has more files, it probably has a file for each certificate that's in the bundle. If the bundle isn't working the same as the directory then I'd take that up with alpine.
